# Generated by Django 5.2.8 on 2026-08-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15)),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('lock_type', models.CharField(choices=[('NONE', 'No Lock'), ('COUNTDOWN', 'Time Countdown'), ('CODE', 'Secret Passcode')], default='NONE', max_length=15)),
                ('unlock_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_code', models.CharField(blank=True, default='', max_length=50)),
                ('cryptic_hint', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
