# Generated by Django 5.2.8 on 2026-08-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Joel D.', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
